# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
prox_sgl <- function(nobs, x, r, b, al, gamma, pf, peps, gw, step) {
    .Call(`_midasml_prox_sgl`, nobs, x, r, b, al, gamma, pf, peps, gw, step)
}

